### ISSUE TITLE
Error Log: Unhandable information found in DoReadDevices : "childLockEnabled" with value : false

### ISSUE THREAD

**Issue by Solilord** [DrozmotiX/ioBroker.tado#206]
Hey, iam permanently getting this warning:
(23327) Send this info to developer !!! { Unhandable information found in DoReadDevices : "childLockEnabled" with value : false

i've got adapter verion 0.2.6 (newest)

Thanks! :)

**Comment by HGlab01** [comment]
Hi! Please check and maybe reinstall your adapter installation because the attribute is definitely covered in this version.
https://github.com/DrozmotiX/ioBroker.tado/blob/43fe97c1b0d70717f89f70e48ae6f3c0f4a90105/lib/state_attr.js#L406-L410
I do not believe it is an adapter issue but maybe an installation issue.
Thanks!

**Comment by Solilord** [comment]
Hey!

The problem is fixed in 0.2.6 but iobroker didnt want to update.
I triggered it manually with the github url and now its working!

`sudo iobroker url "https://github.com/HGlab01/ioBroker.tado"`
It didnt work without sudo. (strange... )


Thanks!
