### ISSUE TITLE
warning 26532 AA_7_DAYS_FREE_Trial

### ISSUE THREAD

**Issue by FlulF** [DrozmotiX/ioBroker.tado#277]
I receive the following warning from tado.
As anyone has the same?!?

**(26532) Send this info to developer !!! { Unhandable information found in DoHome: "enabledFeatures" with value: ["AA_7_DAYS_FREE_TRIAL"]**

**Versions:**  
Version 0.2.6-2 
node: v12.18.0, 
js-controller: 3.2.16

**Additional context**  
It is not really a problem as all scripts running well, but wanted to share that it pop up on my site.
I also installed the last version of tado 3.0 but warning was the same.

**Comment by HGlab01** [comment]
Please update to v0.3.0. In this version the attribute is supported (#226)

**Comment by FlulF** [comment]
HGlab01 thanks for feedback.
I upgraded to version v.0.3.0 and still receive the same warning.

(27311) Send this info to developer !!! { Unhandable information found in DoHome: "enabledFeatures" with value: ["AA_7_DAYS_FREE_TRIAL"]

**Comment by HGlab01** [comment]
Please doublecheck the update / installed version. This warning does not even exist since v0.3.0
When you restart the adapter you can see in the log the installed version. I guess it is still the old one.
If it shows v0.3.x then I recommend to uninstall the adapter and install again.
I am pretty sure that this behavior belongs to versions older than v0.3.0

**Comment by HGlab01** [comment]
I guess it is solved in the meanwhile.
