### ISSUE TITLE
keine Temperatur steuern?

### ISSUE THREAD

**Issue by tommyMX** [DrozmotiX/ioBroker.tado#764]
Hallo,

ich kann keine Temperatur mehr steuern über ein Blockly :-(

Bei den DP zeigt er immer NULL an:
<img width="1599" alt="Bildschirmfoto 2024-01-04 um 19 08 52" src="https://github.com/DrozmotiX/ioBroker.tado/assets/36209886/ac84e655-bcbd-4b6d-ae36-92667ccccf17">
<img width="1589" alt="Bildschirmfoto 2024-01-04 um 19 08 40" src="https://github.com/DrozmotiX/ioBroker.tado/assets/36209886/a56c00b9-388c-4bde-82b6-83233d4a4008">

**Comment by tommyMX** [comment]
`Sentry disabled (debug mode), error catched: State attribute definition missing for 'Stage_09_ZoneStates_data_6' with value '{"tadoMode":"HOME","geolocationOverride":false,"geolocationOverrideDisableTime":null,"preparation":null,"setting":{"type":"HEATING","power":"OFF","temperature":{"celsius":null}},"overlayType":"MANUAL","overlay":{"type":"MANUAL","setting":{"type":"HEATING","power":"OFF","temperature":null},"termination":{"type":"MANUAL","typeSkillBasedApp":"MANUAL","projectedExpiry":null}},"openWindow":null,"nextScheduleChange":{"start":"2024-01-04T23:00:00Z","setting":{"type":"HEATING","power":"ON","temperature":{"celsius":18,"fahrenheit":64.4}}},"nextTimeBlock":{"start":"2024-01-04T23:00:00.000Z"},"link":{"state":"ONLINE"},"activityDataPoints":{"heatingPower":{"type":"PERCENTAGE","percentage":0,"timestamp":"2024-01-04T18:05:40.868Z"}},"sensorDataPoints":{"insideTemperature":{"celsius":21.51,"fahrenheit":70.72,"timestamp":"2024-01-04T18:06:59.872Z","type":"TEMPERATURE","precision":{"celsius":0.1,"fahrenheit":0.1}},"humidity":{"type":"PERCENTAGE","percentage":36.5,"timestamp":"2024-01-04T18:06:59.872Z"}},"overlayClearZone":false,"activateOpenWindow":false}' and type of value 'string'`

**Comment by HGlab01** [comment]
welche Version?
Hast du ein Versionupgrade durchgeführt?

Das Template gibt es aus gutem Grund

**!!! Before you start !!!**  
1. Verify if there is not already an issue requesting the same
2. Is this really a bug of current code, or an enhancement request ?

**Describe the bug**  
A clear and concise description of what the bug is.

**To Reproduce**  
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '....'
4. See error

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Add any other context about the problem here.

**Comment by tommyMX** [comment]
Diese tausend template fragen als ob das was bringt und ewig zum ausfüllen 

Ja war ein Update 

das Problem ist dass der Regler auf off war 

aber dann sollt halt nicht null drin stehen sondern vielleicht off dann weiß man wenigstens gleich was Sache ist !!!!!!
